version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "got"
    groups:
      dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      dev-dependencies:
        dependency-type: development
