# To publish you need a draft release with a tag version corresponding to the version in package.json.
# For more details : https://www.electron.build/configuration/publish.html#recommended-github-releases-workflow

name: Release

on:
  workflow_dispatch:
  push:
    branches: main
    paths: "package.json"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - node: 20
          - os: macos-latest
            dist: dist-mac
          - os: ubuntu-latest
            dist: dist-linux
          - os: windows-latest
            dist: dist-win

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: |
        npm ci
    - name: Build and publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_ID: ${{ secrets.DISCORD_ID }}
      run: |
        npm run ${{ matrix.dist }}
